apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nats
  name: nats
  namespace: pubsub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  strategy: {}
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - image: nats:2.12.1-scratch
        name: nats
        args: ["-js", "--debug"]
        ports:
        - containerPort: 4222
        resources: {}
status: {}
