apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pubsub
resources:
- config.yaml
- statefulset.yaml
- service.yaml
- namespace.yaml

configMapGenerator:
  - name: stream-config
    files:
      - stream-config.json

generatorOptions:
  disableNameSuffixHash: false
