apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-stream-scans
  namespace: pubsub
data:
  scans-stream.json: |
    {
      "name": "SCANS",
      "subjects": [
        "scans.requests",
        "scans.requests_priority",
        "scans.discovery",
        "scans.add_domain_to_easm",
        "scans.dns_scanner_results",
        "scans.dns_processor_results",
        "scans.dns_processor_results_priority",
        "scans.web_scanner_results",
        "scans.web_processor_results"
      ],
      "retention": "workq",
      "storage": "file",
      "discard": "old",
      "max_msgs": -1,
      "max_bytes": "24GB",
      "max_age": "7d",
      "max_msg_size": 0
    }
