apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: gcr.io/track-compliance/api
  newTag: master-4003aac
- name: gcr.io/track-compliance/api-js
  newTag: master-0436952
- name: gcr.io/track-compliance/autoscan
  newTag: master-0000000
- name: gcr.io/track-compliance/db-migration
  newTag: master-0000000
- name: gcr.io/track-compliance/dns
  newTag: master-0000000
- name: gcr.io/track-compliance/frontend
  newTag: master-8778d70
- name: gcr.io/track-compliance/https
  newTag: master-0000000
- name: gcr.io/track-compliance/result-queue
  newTag: master-0000000
- name: gcr.io/track-compliance/results
  newTag: master-0000000
- name: gcr.io/track-compliance/scan-queue
  newTag: master-0000000
- name: gcr.io/track-compliance/ssl
  newTag: master-0000000
resources:
- knative/config/queues.yaml
- knative/config/config.yaml
- knative/config/autoscan.yaml
- knative/config/core.yaml
- knative/monitoring/prometheus.yaml
- knative/monitoring/loki-stack.yaml
- knative/monitoring/grafana/grafana.yaml
- api-namespace.yaml
- frontend-namespace.yaml
- scanners-namespace.yaml
- db-namespace.yaml
- tracker-api-deployment.yaml
- tracker-api-service.yaml
- tracker-api-virtual-service.yaml
- tracker-frontend-deployment.yaml
- tracker-frontend-service.yaml
- tracker-frontend-virtual-service.yaml
- publicgateway.yaml
- certificate.yaml
- arangodb-operator.yaml
- arangodb-deployment.yaml
