---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageRepository
metadata:
  name: super-admin
  namespace: flux-system
spec:
  image: gcr.io/track-compliance/super-admin
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: super-admin
  namespace: flux-system
spec:
  filterTags:
    extract: $ts
    pattern: ^master-[a-fA-F0-9]+-(?P<ts>.*)
  imageRepositoryRef:
    name: super-admin
  policy:
    numerical:
      order: asc
