jobs:
  tracker:
    docker:
      - image: "circleci/python:3.6"
      - image: "mongo:3.6.2"
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          key: "deps1-{{ .Branch }}-{{ checksum \"requirements.txt\" }}"
      - run:
          command: |
              python3 -m venv .env
              . .env/bin/activate
              pip install -r requirements.txt
              pip install -e .[development]
          name: "Installing dependencies"
      - save_cache:
          key: "deps1-{{ .Branch }}-{{ checksum \"requirements.txt\" }}"
          paths:
            - .env
      - run:
          command: |
              . .env/bin/activate
              pylint data tests 
              # mypy src tests
              pytest --cov=data tests
          name: "Running tests"
    working_directory: ~/repo
  build_package:
    docker:
      - image: cdssnc/tracker-build:0.1.0
    working_directory: /home/DEV.T1.TBS-SCT.GC.CA/dsamojle-ps
    steps:
      - checkout
      - run:
          command: sh deploy/build-env.sh
          name: "Building the package"
      - store_artifacts:
          path: /home/DEV.T1.TBS-SCT.GC.CA/dsamojle-ps/tracker.tar.gz
          destination: tracker.tar.gz
workflows:
  version: 2
  tracker:
    jobs:
      - tracker
      - build_package:
         requires:
            - tracker
         filters:
           branches:
             only: master
