jobs:
  track_digital:
    docker:
      - image: "circleci/python:3.6.1"
      - image: "mongo:3.6.2"
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          key: "deps1-{{ .Branch }}-{{ checksum \"requirements.txt\" }}"
      - run:
          command: |
              python3 -m venv .env
              . .env/bin/activate
              pip install -r requirements.txt
              pip install -e .[development]
          name: "Installing dependencies"
      - save_cache:
          key: "deps1-{{ .Branch }}-{{ checksum \"requirements.txt\" }}"
          paths:
            - .env
      - run:
          command: |
              . .env/bin/activate
              # pylint src tests -- Major overhaul needed to not fail linting, not including linting in tests for now
              # mypy src tests
              pytest --cov=track tests
          name: "Running tests"
    working_directory: ~/repo/track_digital
  data:
    docker:
      - image: "circleci/python:3.6.1"
      - image: "mongo:3.6.2"
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          key: "deps1-{{ .Branch }}-{{ checksum \"requirements.txt\" }}"
      - run:
          command: |
              python3 -m venv .env
              . .env/bin/activate
              pip install -r requirements.txt
              pip install -e .[development]
          name: "Installing dependencies"
      - save_cache:
          key: "deps1-{{ .Branch }}-{{ checksum \"requirements.txt\" }}"
          paths:
            - .env
      - run:
          command: |
              . .env/bin/activate
              # pylint src tests -- Major overhaul needed to not fail linting, not including linting in tests for now
              # mypy src tests
              pytest --cov=data tests
          name: "Running tests"
    working_directory: ~/repo/tracker
  deploy_site:
    docker:
      - image: docker:17.12.1-ce-git
    steps:
      - checkout:
          path: ~/repo
      - setup_remote_docker
      - run:
          command: |
              docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
              docker build  -t "${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}" -t "${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/${CIRCLE_PROJECT_REPONAME}:latest" .
              docker push "${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}"
              docker push "${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/${CIRCLE_PROJECT_REPONAME}:latest"
          name: "Build and Deploy Website Docker Image"
    working_directory: ~/repo/track_digital

workflows:
  version: 2
  tracker:
    jobs:
      - track_digital 
      - data
      - deploy_site:
          filters:
            branches:
              only:
                - master
          requires:
            - track_digital
            - data
