jobs:
  tracker:
    docker:
      - image: "circleci/python:3.5.5"
      - image: "mongo:3.6.2"
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          key: "deps1-{{ .Branch }}-{{ checksum \"requirements.txt\" }}"
      - run:
          command: |
              python3 -m venv .env
              . .env/bin/activate
              pip install -r requirements.txt
              pip install -e .[development]
          name: "Installing dependencies"
      - save_cache:
          key: "deps1-{{ .Branch }}-{{ checksum \"requirements.txt\" }}"
          paths:
            - .env
      - run:
          command: |
              . .env/bin/activate
              pylint data tests 
              # mypy src tests
              pytest --cov=data tests
          name: "Running tests"
    working_directory: ~/repo
  build_package:
    docker:
      - image: ubuntu:xenial
    working_directory: /home/DEV.T1.TBS-SCT.GC.CA/dsamojle-ps
    steps:
      - checkout
      - run:
          command: |
              apt-get update
              apt-get install -y python3 python3-venv python3-dev build-essential wget
              apt-get install -y python3-pip locales
              locale-gen en_US.UTF-8
              export LANG="en_US:en"
              export LANGUAGE="en_US: en"
              export LC_ALL="en_US.UTF-8"

              mkdir -p domain-scan && wget -q -O - https://api.github.com/repos/18F/domain-scan/tarball | tar xz --strip-components=1 -C domain-scan
              python3 -m venv .venv
              . .venv/bin/activate
              pip install --upgrade pip
              pip install -r requirements.txt
              pip install -r domain-scan/requirements.txt
              pip install -r domain-scan/requirements-scanners.txt
              pip install .
              tar -czvf tracker.tar.gz .venv domain-scan
      - store_artifacts:
          path: /home/DEV.T1.TBS-SCT.GC.CA/dsamojle-ps/tracker.tar.gz
          destination: tracker.tar.gz
workflows:
  version: 2
  tracker:
    jobs:
      - tracker
      - build_package:
         requires:
            - tracker
         filters:
           branches:
             only: master
