apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesJSON6902:
- target:
    group: install.istio.io
    version: v1alpha1
    kind: IstioOperator
    name: istio-controlplane
    namespace: istio-operator
  patch: |-
    - op: remove
      path: /spec/components/pilot
