apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: gcr.io/track-compliance/api
  newTag: master-4003aac
- name: gcr.io/track-compliance/autoscan
  newTag: master-0000000
- name: gcr.io/track-compliance/db-migration
  newTag: master-0000000
- name: gcr.io/track-compliance/dns
  newTag: master-0000000
- name: gcr.io/track-compliance/frontend
  newTag: master-dfedbf0
- name: gcr.io/track-compliance/https
  newTag: master-0000000
- name: gcr.io/track-compliance/result-queue
  newTag: master-0000000
- name: gcr.io/track-compliance/results
  newTag: master-0000000
- name: gcr.io/track-compliance/scan-queue
  newTag: master-0000000
- name: gcr.io/track-compliance/ssl
  newTag: master-0000000
resources:
- knative/config/domain-config.yaml
- knative/config/queues.yaml
- knative/config/config.yaml
- knative/config/autoscan.yaml
- knative/monitoring/prometheus.yaml
- knative/monitoring/loki-stack.yaml
- knative/monitoring/grafana/grafana.yaml
- tracker-api-deployment.yaml
- tracker-api-service.yaml
- tracker-api-virtual-service.yaml
- tracker-frontend-deployment.yaml
- tracker-frontend-service.yaml
- tracker-frontend-virtual-service.yaml
- istio.yaml
- envoy-filter.yaml
- publicgateway.yaml
- postgres-deployment.yaml
- postgres-pvc.yaml
- postgres-service.yaml
- certificate.yaml
- cert-manager.yaml
- cluster-admin-rolebinding.yaml
- http-01-challenge-destination-rule.yaml
- api-namespace.yaml
- frontend-namespace.yaml
- istio-system-namespace.yaml
- knative-serving-namespace.yaml
- scanners-namespace.yaml
