apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- envoy-gzip.yaml
- envoy-security-headers-filter.yaml
- istio.yaml
- http-01-challenge-destination-rule.yaml
patchesStrategicMerge:
# remove extra status ports from ingress service
- istio-ingressgateway-service.yaml
