apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../bases
- storage-classes.yaml
- backup-service-account.yaml
- backup-cronjob.yaml
patchesStrategicMerge:
- arangodb-deployment.yaml
- tracker-api-deployment.yaml
- tracker-frontend-deployment.yaml
- publicgateway.yaml
- certificate.yaml
replicas:
- name: tracker-frontend
  count: 2
- name: tracker-api
  count: 2
- name: arango-deployment-replication-operator
  count: 1
- name: arango-deployment-operator
  count: 1
- name: arango-storage-operator
  count: 1
components:
- ../namespaces
