apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../bases
- api-image-policy.yaml
- frontend-image-policy.yaml
- autoscan-image-policy.yaml
- dmarc-report-image-policy.yaml
- result-processor-image-policy.yaml
- update-automation.yaml
patches:
- path: tracker-repo.yaml
