apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../bases
- api-image-policy.yaml
- frontend-image-policy.yaml
- autoscan-image-policy.yaml
- dmarc-report-image-policy.yaml
- dns-scanner-image-policy.yaml
- https-scanner-image-policy.yaml
- result-processor-image-policy.yaml
- ssl-scanner-image-policy.yaml
- update-automation.yaml
- summaries-image-policy.yaml
- guidance-image-policy.yaml
- super-admin-image-policy.yaml
- queue-image-policies.yaml
patchesStrategicMerge:
- tracker-repo.yaml
