apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: db

resources:
- https://raw.githubusercontent.com/arangodb/kube-arangodb/1.2.6/manifests/arango-crd.yaml
- https://raw.githubusercontent.com/arangodb/kube-arangodb/1.2.6/manifests/arango-deployment.yaml
- https://raw.githubusercontent.com/arangodb/kube-arangodb/1.2.6/manifests/arango-storage.yaml
- https://raw.githubusercontent.com/arangodb/kube-arangodb/1.2.6/manifests/arango-deployment-replication.yaml
