---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageRepository
metadata:
  name: dns-scanner
  namespace: flux-system
spec:
  image: gcr.io/track-compliance/services/scanners/dns
  interval: 1m0s

