apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux.yaml
- api-registry.yaml
- frontend-registry.yaml
- autoscan-registry.yaml
- dmarc-report-registry.yaml
- result-processor-registry.yaml
- tracker-repo.yaml
- app-kustomization.yaml
- platform-kustomization.yaml
