apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux.yaml
- api-registry.yaml
- frontend-registry.yaml
- autoscan-registry.yaml
- dmarc-report-registry.yaml
- dns-scanner-registry.yaml
- https-scanner-registry.yaml
- result-processor-registry.yaml
- ssl-scanner-registry.yaml
- tracker-repo.yaml
- app-kustomization.yaml
- platform-kustomization.yaml
- summaries-registry.yaml
- guidance-registry.yaml
- super-admin-registry.yaml
