apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- arangodb-deployment.yaml

#replicas:
#- name: arango-deployment-replication-operator
#  count: 1
#- name: arango-deployment-operator
#  count: 1
#- name: arango-storage-operator
#  count: 1
