apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: db
resources:
  - arangodb-deployment.yaml
#- ../../bases
#patchesStrategicMerge:
#- arangodb-deployment.yaml
#replicas:
##- name: tracker-frontend
##  count: 1
##- name: tracker-api
##  count: 1
#- name: arango-deployment-replication-operator
#  count: 1
#- name: arango-deployment-operator
#  count: 1
#- name: arango-storage-operator
#  count: 1
