apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../bases
- cert-manager.yaml
- certificate.yaml
- letsencrypt-issuer.yaml
images:
- name: gcr.io/track-compliance/api
  newTag: master-4301b10
- name: gcr.io/track-compliance/frontend
  newTag: master-7ad6cbc
patchesStrategicMerge:
- tracker-api-deployment.yaml
- tracker-frontend-deployment.yaml
- istio.yaml
- publicgateway.yaml
