apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../bases
- ingressgateway.yaml
- cert-manager.yaml
- certificate.yaml
- letsencrypt-issuer.yaml
images:
- name: gcr.io/track-compliance/api
  newTag: master-edcdbde
- name: gcr.io/track-compliance/frontend
  newTag: master-01955fa
patchesStrategicMerge:
- tracker-api-deployment.yaml
- tracker-frontend-deployment.yaml
