apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../bases
- cert-manager.yaml
- certificate.yaml
- letsencrypt-issuer.yaml
- knative/config/domain-config.yaml
- knative/config/config.yaml
- knative/config/autoscan.yaml
- knative/monitoring/prometheus.yaml
- knative/monitoring/grafana/grafana.yaml
- pgo/operatorconfiguration.crd.yaml
- pgo/postgresql.crd.yaml
- pgo/api-service.yaml
- pgo/operator-service-account-rbac.yaml
- pgo/postgres-operator.yaml
- pgo/postgresql-operator-default-configuration.yaml
- http-01-challenge-destination-rule.yaml
images:
- name: gcr.io/track-compliance/api
  newTag: master-29fe623
- name: gcr.io/track-compliance/frontend
  newTag: master-8a93fb6
patchesStrategicMerge:
- tracker-api-deployment.yaml
- tracker-frontend-deployment.yaml
- istio.yaml
- publicgateway.yaml
