apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../bases
- letsencrypt-issuer.yaml
- cert-manager.yaml
- certificate.yaml
- http-01-challenge-destination-rule.yaml
images:
- name: gcr.io/track-compliance/api
  newTag: master-4003aac
- name: gcr.io/track-compliance/frontend
  newTag: master-8090829
patchesStrategicMerge:
- tracker-api-deployment.yaml
- tracker-frontend-deployment.yaml
- istio-ingressgateway-service.yaml
- publicgateway.yaml
