apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../bases
- cert-manager.yaml
- certificate.yaml
- letsencrypt-issuer.yaml
- knative/config/config.yaml
- knative/monitoring/prometheus.yaml
- knative/monitoring/grafana/grafana.yaml
- knative/monitoring/node-exporter.yaml
images:
- name: gcr.io/track-compliance/api
  newTag: master-25073f1
- name: gcr.io/track-compliance/frontend
  newTag: master-19a3add
patchesStrategicMerge:
- tracker-api-deployment.yaml
- tracker-frontend-deployment.yaml
- istio.yaml
- publicgateway.yaml
