apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../bases
- cert-manager.yaml
- certificate.yaml
- letsencrypt-issuer.yaml
- publicgateway.yaml
images:
- name: gcr.io/track-compliance/api
  newTag: master-aef801b
- name: gcr.io/track-compliance/frontend
  newTag: master-d13cda0
patchesStrategicMerge:
- tracker-api-deployment.yaml
- tracker-frontend-deployment.yaml
- tracker-api-virtual-service.yaml
- tracker-frontend-virtual-service.yaml
- istio.yaml
- envoy-filter.yaml
